namespace CCompiler {
  public enum MiddleOperator {/*Block, If, IfElse, Switch, Case, Default, Break,
                              Continue, While, Do, For, Label,*/ Goto,
                              AssignRegister, /*SaveFromRegister,*/ Compare,
                              InspectFlagbyte, InspectRegister, SysCall,
                              JumpRegister, Interrupt, Expression, Declaration,
                              PushZero, PushOne, PushFloat, PopFloat, TopFloat,
                              PopEmpty, Comma, Assign, LogicalOr, LogicalAnd,
                              BitwiseOr, BitwiseXOr, BitwiseAnd,
                              Equal, EqualZero, NotEqual, SignedLessThan,
                              SignedLessThanEqual, SignedGreaterThan,
                              SignedGreaterThanEqual, UnsignedLessThan,
                              UnsignedLessThanEqual, UnsignedGreaterThan,
                              UnsignedGreaterThanEqual, ShiftLeft,
                              ShiftRight, BinaryAdd, BinarySubtract,
                              SignedMultiply, SignedDivide, SignedModulo,
                              UnsignedMultiply, UnsignedDivide, UnsignedModulo,
                              UnaryAdd, UnarySubtract, Carry, NotCarry,
                              LogicalNot, BitwiseNot, Address, Dereference,
                              Call, PostCall, DecreaseStack, CheckTrackMapFloatStack,
                              Parameter, Empty, Return, Increment, Decrement, Exit, PreCall,
                              FunctionEnd, //SystemInitializer, SystemParameter,
                              Conditional, SetReturnValue, GetReturnValue,
                              IntegralToIntegral, IntegralToFloating, FloatingToIntegral,
                              ArrayToPointer, FunctionToPointer, StringToPointer,
                              ValueOffset, AddressOffset, /*CarryFlag,*/ Case, CaseEnd,
                              Index, Dot, Arrow, Variable, Value, Initializer, InitializerZero};
}